export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL'
export const GET_FRIENDS_REQUEST = 'FRIENDS/GET_FRIENDS_REQUEST'
export const GET_FRIENDS_SUCCESS = 'FRIENDS/GET_FRIENDS_SUCCESS'
export const GET_FRIENDS_FAIL = 'FRIENDS/GET_FRIENDS_FAIL'

